// geochk_small.cpp — C++ translation of geochk.F90 subprograms:
//   fix_charges (lines 1580-1636),
//   add_sp_H    (lines 1637-1665),
//   add_sp2_H   (lines 1666-1694),
//   add_sp3_H   (lines 1695-1723).
// 1-based Fortran indexing is kept for all module arrays.
#include "geochk.h"

#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

#include "chanel_C.h"
#include "common_arrays_C.h"
#include "molkst_C.h"
#include "upcase.h"

namespace mc = common_arrays_C;
namespace mk = molkst_C;
namespace ch = chanel_C;

// Fortran len_trim: length without trailing blanks.
static std::size_t len_trim(const std::string& s) {
  std::size_t e = s.find_last_not_of(' ');
  return e == std::string::npos ? 0 : e + 1;
}

// 1-based Fortran index().
static int index1(const std::string& s, const std::string& sub) {
  std::size_t p = s.find(sub);
  return p == std::string::npos ? 0 : static_cast<int>(p) + 1;
}

// Build the 12-character field written by
//   write(x(i:i+11),'(" CHARGE=",iN)') ichrge
// e.g. " CHARGE=  -5   ".
static std::string fmt_charge_field(int ichrge) {
  char buf[32];
  if (ichrge > 99)      std::snprintf(buf, sizeof buf, " CHARGE=%3d", ichrge);
  else if (ichrge > 9)  std::snprintf(buf, sizeof buf, " CHARGE=%2d", ichrge);
  else if (ichrge > 0)  std::snprintf(buf, sizeof buf, " CHARGE=%1d", ichrge);
  else if (ichrge > -10) std::snprintf(buf, sizeof buf, " CHARGE=%2d", ichrge);
  else                  std::snprintf(buf, sizeof buf, " CHARGE=%3d", ichrge);
  std::string s(buf);
  while (s.size() < 12) s += ' ';
  return s;
}

// Remove an existing " CHARGE=n" segment from str (1-based Fortran str(i+1:)
// semantics) and return the position (1-based) of the 12-blank field.
static int strip_charge(std::string& s) {
  int i = index1(s, " CHARGE=");
  if (i != 0) {
    int j = index1(s.substr(i + 1), " ");
    if (j > 0) {
      // refkey(i+1:) = refkey(i+j+2:)  => erase 1-based [i+1 .. i+j+1]
      int a = i;            // 0-based start of " CHARGE="
      int b = i + j;        // 0-based one past last char of " CHARGE=..."
      s.erase(a, b - a);
    }
  }
  // Find 12 consecutive blanks (the write target).
  int k = index1(s, "            ");  // 12 spaces
  return k;
}

void fix_charges(int ichrge) {
  mk::line = mk::refkey[1];
  upcase(mk::line, static_cast<int>(len_trim(mk::line)));
  int i = index1(mk::line, " CHARGE=");
  if (i != 0) {
    int j = index1(mk::refkey[1].substr(i + 1), " ");
    if (j > 0) {
      // refkey(i+1:) = refkey(i+j+2:): shift left by j+1, blanking the tail.
      mk::refkey[1].erase(i, j + 1);
    }
  }
  // Find 12 blanks in refkey(1) and write the new CHARGE there.
  i = index1(mk::refkey[1], "            ");
  if (i != 0 && ichrge != 0) {
    mk::refkey[1].replace(i - 1, 12, fmt_charge_field(ichrge));
  }
  i = index1(mk::keywrd, " CHARGE=");
  if (i != 0) {
    int j = index1(mk::keywrd.substr(i + 1), " ");
    if (j > 0) {
      mk::keywrd.erase(i, j + 1);
    }
  }
  i = index1(mk::keywrd, "            ");
  if (i != 0 && ichrge != 0) {
    mk::keywrd.replace(i - 1, 12, fmt_charge_field(ichrge));
  }
}

static void add_H_common(int new_atom, int i_anchor, bool& first) {
  // new_atom: the natoms slot just created; i_anchor: atom used for scaling.
  mc::nat[new_atom] = 1;
  mc::txtatm[new_atom] = " ";
  (void)i_anchor; (void)first;
}

void add_sp_H(int i1, int i, int i2) {
  static bool first = true;
  mk::natoms = mk::natoms + 1;
  if (mk::natoms > mk::maxatoms) {
    if (first) {
      std::fprintf(stdout, " Too many changes. Re-run using the data set generated by this job\n");
      first = false;
    }
    mk::natoms = mk::natoms - 1;
    return;
  }
  // geo(:,natoms) = 2*geo(:,i1) - 2*geo(:,i) + geo(:,i2)
  for (int k = 1; k <= 3; ++k) {
    mc::geo[k][mk::natoms] = 2.0 * mc::geo[k][i1] - 2.0 * mc::geo[k][i] + mc::geo[k][i2];
  }
  double dx = mc::geo[1][i1] - mc::geo[1][mk::natoms];
  double dy = mc::geo[2][i1] - mc::geo[2][mk::natoms];
  double dz = mc::geo[3][i1] - mc::geo[3][mk::natoms];
  double scale = 1.1 / std::sqrt(dx * dx + dy * dy + dz * dz);
  for (int k = 1; k <= 3; ++k) {
    mc::geo[k][mk::natoms] = mc::geo[k][i1] + scale * (mc::geo[k][mk::natoms] - mc::geo[k][i1]);
  }
  add_H_common(mk::natoms, i1, first);
}

void add_sp2_H(int i1, int i, int i2) {
  static bool first = true;
  mk::natoms = mk::natoms + 1;
  if (mk::natoms > mk::maxatoms) {
    if (first) {
      std::fprintf(stdout, " Too many changes. Re-run using the data set generated by this job\n");
      first = false;
    }
    mk::natoms = mk::natoms - 1;
    return;
  }
  // geo(:,natoms) = 3*geo(:,i) - geo(:,i1) - geo(:,i2)
  for (int k = 1; k <= 3; ++k) {
    mc::geo[k][mk::natoms] = 3.0 * mc::geo[k][i] - mc::geo[k][i1] - mc::geo[k][i2];
  }
  double dx = mc::geo[1][i] - mc::geo[1][mk::natoms];
  double dy = mc::geo[2][i] - mc::geo[2][mk::natoms];
  double dz = mc::geo[3][i] - mc::geo[3][mk::natoms];
  double scale = 1.1 / std::sqrt(dx * dx + dy * dy + dz * dz);
  for (int k = 1; k <= 3; ++k) {
    mc::geo[k][mk::natoms] = mc::geo[k][i] + scale * (mc::geo[k][mk::natoms] - mc::geo[k][i]);
  }
  add_H_common(mk::natoms, i, first);
}

void add_sp3_H(int i1, int i, int i2, int i3) {
  static bool first = true;
  mk::natoms = mk::natoms + 1;
  if (mk::natoms > mk::maxatoms) {
    if (first) {
      std::fprintf(stdout, " Too many changes. Re-run using the data set generated by this job\n");
      first = false;
    }
    mk::natoms = mk::natoms - 1;
    return;
  }
  // geo(:,natoms) = 4*geo(:,i) - geo(:,i1) - geo(:,i2) - geo(:,i3)
  for (int k = 1; k <= 3; ++k) {
    mc::geo[k][mk::natoms] = 4.0 * mc::geo[k][i] - mc::geo[k][i1] - mc::geo[k][i2] - mc::geo[k][i3];
  }
  double dx = mc::geo[1][i] - mc::geo[1][mk::natoms];
  double dy = mc::geo[2][i] - mc::geo[2][mk::natoms];
  double dz = mc::geo[3][i] - mc::geo[3][mk::natoms];
  double scale = 1.1 / std::sqrt(dx * dx + dy * dy + dz * dz);
  for (int k = 1; k <= 3; ++k) {
    mc::geo[k][mk::natoms] = mc::geo[k][i] + scale * (mc::geo[k][mk::natoms] - mc::geo[k][i]);
  }
  add_H_common(mk::natoms, i, first);
}
